#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Ubuntu, 3.13.0-35-generic, RT-tuned' --class ubuntu --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-3.13.0-35-generic-advanced-0aacdd00-1ecc-48d0-8ab2-c89683f8604d' {
	recordfail
	load_video
	gfxmode $linux_gfx_mode
	insmod gzio
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos2'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos2 --hint-efi=hd0,msdos2 --hint-baremetal=ahci0,msdos2  0aacdd00-1ecc-48d0-8ab2-c89683f8604d
	else
	  search --no-floppy --fs-uuid --set=root 0aacdd00-1ecc-48d0-8ab2-c89683f8604d
	fi
	echo	'Loading Linux 3.13.0-35-generic RT-tuned...'
	linux	/boot/vmlinuz-3.13.0-35-generic root=UUID=0aacdd00-1ecc-48d0-8ab2-c89683f8604d ro  quiet splash $vt_handoff default_hugepagesz=2M hugepages=2048 hugepagesz=2M 
	echo	'Loading initial ramdisk ...'
	initrd	/boot/initrd.img-3.13.0-35-generic
}
