export http_proxy="http://proxy.ch.intel.com:911"
export https_proxy="http://proxy.ch.intel.com:911"
export ftp_proxy="http://proxy.ch.intel.com:911"
export HTTP_PROXY="http://proxy.ch.intel.com:911" 
export NO_PROXY="localhost,127.0.0.0/8"
